Repository neul-poom/backend, pull requests merged in 2024-07, with the labels that each got.

#30 Refactor/#27 auth
  module_api_gateway/build.gradle
  module_api_gateway/src/main/java/com/jk/module_api_gateway/ModuleApiGatewayApplication.java
  module_api_gateway/src/main/java/com/jk/module_api_gateway/auth/AuthorizationHeaderFilter.java
  module_api_gateway/src/main/java/com/jk/module_api_gateway/auth/LoggingFilter.java
  module_api_gateway/src/main/java/com/jk/module_api_gateway/auth/TokenValidator.java
  module_api_gateway/src/main/java/com/jk/module_api_gateway/config/FilterConfig.java
  module_user/build.gradle
  module_user/src/main/java/com/jk/module_user/ModuleUserApplication.java
  module_user/src/main/java/com/jk/module_user/auth/config/SecurityConfig.java
  module_user/src/main/java/com/jk/module_user/auth/controller/RefreshTokenController.java
  module_user/src/main/java/com/jk/module_user/auth/controller/UserLoginController.java
  module_user/src/main/java/com/jk/module_user/auth/dto/UserLoginRequestDto.java
  module_user/src/main/java/com/jk/module_user/auth/filter/JwtAuthenticationFilter.java
  module_user/src/main/java/com/jk/module_user/auth/filter/JwtAuthorizationFilter.java
  module_user/src/main/java/com/jk/module_user/auth/jwt/JwtAuthenticationFilter.java
  module_user/src/main/java/com/jk/module_user/auth/jwt/JwtTokenDto.java
  module_user/src/main/java/com/jk/module_user/auth/jwt/JwtTokenProvider.java
  module_user/src/main/java/com/jk/module_user/auth/jwt/JwtUtil.java
  module_user/src/main/java/com/jk/module_user/auth/security/UserDetailsImpl.java
  module_user/src/main/java/com/jk/module_user/auth/security/UserDetailsServiceImpl.java
  module_user/src/main/java/com/jk/module_user/auth/security/WebSecurityConfig.java
  module_user/src/main/java/com/jk/module_user/auth/service/RefreshTokenService.java
  module_user/src/main/java/com/jk/module_user/auth/service/UserLoginService.java
  module_user/src/main/java/com/jk/module_user/user/controller/UserController.java
  module_user/src/main/java/com/jk/module_user/user/dto/request/UserLoginRequestDto.java
  module_user/src/main/java/com/jk/module_user/user/dto/request/UserPasswordRequestDto.java
  module_user/src/main/java/com/jk/module_user/user/dto/request/UserSignupRequestDto.java
  module_user/src/main/java/com/jk/module_user/user/dto/request/UserUpdateRequestDto.java
  module_user/src/main/java/com/jk/module_user/user/dto/response/UserInfoResponseDto.java
  module_user/src/main/java/com/jk/module_user/user/dto/response/UserLoginResponseDto.java
  module_user/src/main/java/com/jk/module_user/user/dto/response/UserSignupResponseDto.java
  module_user/src/main/java/com/jk/module_user/user/dto/response/UserUpdateResponseDto.java
  module_user/src/main/java/com/jk/module_user/user/entity/User.java
  module_user/src/main/java/com/jk/module_user/user/repository/UserRepository.java
  module_user/src/main/java/com/jk/module_user/user/security/UserDetailsServiceImpl.java
  module_user/src/main/java/com/jk/module_user/user/service/UserService.java
  module_user/src/main/resources/application.yml
Labels: refactor

#32 Refactor/#31 email certification
  docker-compose.yml
  module_api_gateway/src/main/java/com/jk/module_api_gateway/config/FilterConfig.java
  module_user/build.gradle
  module_user/src/main/java/com/jk/module_user/auth/jwt/JwtAuthenticationFilter.java
  module_user/src/main/java/com/jk/module_user/common/email/config/EmailConfig.java
  module_user/src/main/java/com/jk/module_user/common/email/controller/EmailController.java
  module_user/src/main/java/com/jk/module_user/common/email/dto/request/EmailVerificationRequestDto.java
  module_user/src/main/java/com/jk/module_user/common/email/service/EmailService.java
  module_user/src/main/java/com/jk/module_user/common/redis/config/RedisConfig.java
  module_user/src/main/java/com/jk/module_user/common/redis/service/RedisService.java
  module_user/src/main/java/com/jk/module_user/user/dto/request/UserSignupRequestDto.java
  module_user/src/main/java/com/jk/module_user/user/service/UserService.java
Labels: refactor

#33 Feat/#28 first come coupon
  module_coupon/build.gradle
  module_coupon/src/main/java/com/jk/module_coupon/common/exception/ErrorCode.java
  module_coupon/src/main/java/com/jk/module_coupon/config/RedisConfig.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/controller/CouponIssuedController.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/domain/Coupon.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/domain/CouponTypeEnum.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/dto/request/CouponCreateRequestDto.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/dto/request/CouponUpdateRequestDto.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/repository/CouponCountRepository.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/service/CouponIssuedService.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/service/CouponService.java
  mysql-init/coupon/init.sql
Labels: refactor

#34 build #28(first_come_coupon): 스프링부트 버전 수정
  module_coupon/build.gradle
Labels: feature

#35 style #28(first_come_coupon): 쿠폰 전체 서비스 주석 스타일 변경
  module_coupon/src/main/java/com/jk/module_coupon/coupon/controller/CouponController.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/controller/CouponIssuedController.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/service/CouponIssuedService.java
  module_coupon/src/main/java/com/jk/module_coupon/coupon/service/CouponService.java
Labels: refactor

#36 feat/#1_join: 회원 정보 수정 dto 변경
  module_user/src/main/java/com/jk/module_user/user/dto/request/UserUpdateRequestDto.java
  module_user/src/main/java/com/jk/module_user/user/service/UserService.java
Labels: feature

#39 Feat/#1 join
  module_user/src/main/java/com/jk/module_user/auth/jwt/JwtAuthenticationFilter.java
  module_user/src/main/java/com/jk/module_user/auth/jwt/JwtTokenProvider.java
  module_user/src/main/java/com/jk/module_user/auth/security/UserDetailsServiceImpl.java
  module_user/src/main/java/com/jk/module_user/auth/service/RefreshTokenService.java
  module_user/src/main/java/com/jk/module_user/auth/service/UserLoginService.java
  module_user/src/main/java/com/jk/module_user/common/exception/CustomException.java
  module_user/src/main/java/com/jk/module_user/common/exception/ErrorCode.java
  module_user/src/main/java/com/jk/module_user/common/exception/ErrorResponse.java
  module_user/src/main/java/com/jk/module_user/common/exception/GlobalExceptionHandler.java
  module_user/src/main/java/com/jk/module_user/user/service/UserService.java
Labels: feature

#41 Refactor/#23 connect lecture module
  module_lecture/build.gradle
  module_lecture/src/main/java/com/jk/module_lecture/ModuleLectureApplication.java
  module_lecture/src/main/java/com/jk/module_lecture/client/LectureResourceClient.java
  module_lecture/src/main/java/com/jk/module_lecture/client/UserClient.java
  module_lecture/src/main/java/com/jk/module_lecture/common/config/FeignConfig.java
  module_lecture/src/main/java/com/jk/module_lecture/common/exception/ErrorCode.java
  module_lecture/src/main/java/com/jk/module_lecture/lecture/controller/InternalLectureController.java
  module_lecture/src/main/java/com/jk/module_lecture/lecture/controller/LectureController.java
  module_lecture/src/main/java/com/jk/module_lecture/lecture/dto/request/LectureCreateRequestDto.java
  module_lecture/src/main/java/com/jk/module_lecture/lecture/dto/request/LectureUpdateRequestDto.java
  module_lecture/src/main/java/com/jk/module_lecture/lecture/dto/response/LectureDetailResponseDto.java
  module_lecture/src/main/java/com/jk/module_lecture/lecture/service/LectureService.java
  module_lecture_resource/build.gradle
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/ModuleLectureResourceApplication.java
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/client/LectureClient.java
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/common/config/FeignConfig.java
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/lecture_note/controller/InternalLectureNoteController.java
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/lecture_note/repository/LectureNoteRepository.java
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/lecture_note/service/LectureNoteService.java
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/multimedia/controller/InternalMultimediaController.java
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/multimedia/repository/MultimediaRepository.java
  module_lecture_resource/src/main/java/com/jk/module_lecture_resource/multimedia/service/MultimediaService.java
Labels: refactor

#43 feat #40(search): docker-compose 파일에 ElasticSearch와 Kibana 설정 코드 추가
  docker-compose.yml
Labels: feature

#46 docs #45: readme 파일 초안 작성
  README.md
  img/erd.png
Labels: docs
